### ISSUE TITLE
Name 'a' is not defined

### ISSUE THREAD

**Issue by SteveDiamond** [mwytock/epsilon#25]
I got this error when solving a problem with epsilon:
```
Traceback (most recent call last):
  File "simulation/discrete_sim.py", line 93, in <module>
    ep.solve(prob)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/cvxpy_solver.py", line 54, in solve
    problem = compiler.compile_problem(problem)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/compiler.py", line 18, in compile_problem
    problem = transform(problem)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/prox.py", line 647, in transform_problem
    f_exprs = list(transform_expr(problem.objective))
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/prox.py", line 640, in transform_expr
    for prox_expr in transform_expr(raw_expr):
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/prox.py", line 632, in transform_expr
    result = rule(expr)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/prox.py", line 562, in transform_cone
    obj, constrs = conic.transform_expr(expr)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 210, in transform_expr
    obj_arg, constr = transform_expr(arg)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 210, in transform_expr
    obj_arg, constr = transform_expr(arg)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 210, in transform_expr
    obj_arg, constr = transform_expr(arg)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 210, in transform_expr
    obj_arg, constr = transform_expr(arg)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 222, in transform_expr
    obj_linear, constr = globals()[f_name](obj_linear)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/compiler/transforms/conic.py", line 202, in transform_exp
    return t, expression.epigraph(expr, t)
  File "/Users/stevend2/anaconda/envs/epsilon/lib/python2.7/site-packages/epopt/expression.py", line 395, in epigraph
    return leq_constraint(a, b)
NameError: global name 'a' is not defined
```
The context is kind of complicated, but here's a script that reproduces the bug:
```
import numpy as np
NUM_TRIALS = 10
T = 100
G1 = G2 =  np.ones((NUM_TRIALS,T))
import cvxpy as cvx
import epopt as ep

r = cvx.Variable(T)
lamb = r
t = cvx.Variable(NUM_TRIALS)
expr = cvx.exp(-G1*lamb)
ll = cvx.sum_entries(cvx.log(expr - cvx.exp(-G2*lamb)))

# gamma.value = 1
r.value = np.ones(T)
t.value = expr.value

theta = 0.95
for i in range(5):
    prev_r = r.value
    linearized = expr.value + (-G1.T*cvx.diag(cvx.exp(-G1*lamb))).value.T*(r - prev_r)
    gain = cvx.sum_entries(cvx.log(linearized - cvx.exp(-G2*lamb)))
    prob = cvx.Problem(cvx.Maximize(gain),
                      [r >= 0])
    ep.solve(prob)
    while np.min(r.value) < 0:
        r.value = theta*r.value + (1-theta)*prev_r
    print prob.value
    print ll.value
```

**Comment by mwytock** [comment]
Thanks for the report!

There is a minor issue due to a typo but the main thing that is happening here is we didn't yet implement the epigraph operator for exp(t) for a few silly reasons. Will add this shortly...

**Comment by mwytock** [comment]
This should be fixed now, but this is a weird problem.. epsilon (as well as SCS/ECOS) seem to return "solutions" such that the term in side the log() is negative...

**Comment by SteveDiamond** [comment]
I think the problem is badly defined. The term inside the log is always non-positive. I was trying to solve 
```
gain = cvx.sum_entries(cvx.log(cvx.exp(-G1*lamb) - cvx.exp(-G2*lamb)))
prob = cvx.Problem(cvx.Maximize(gain),
                                [r >= 0])
```
through difference-of-convex programming, but it doesn't seem possible.

**Comment by SteveDiamond** [comment]
Hey it's actually a convex problem!
```
gain = cvx.sum_entries(-G1*lamb + cvx.log(1- cvx.exp(-G2*lamb+G1*lamb)))
prob = cvx.Problem(cvx.Maximize(gain),
                                [r >= 0])
```
